---
# tasks file for k8s
- debug: var=ansible_distribution
- name: Enable a RHSM repository on Redhat
  rhsm_repository: 
    name: rhel-7-server-extras-rpms
  when: ansible_distribution == 'RedHat'
  ignore_errors: true

- name: Install basic packages on Ubuntu 
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ base_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: Add kubernetes repository on Redhat
  yum_repository:
    name: Kubernetes
    description: Adding Kubernetes repositories
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    enabled: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
  when: ansible_distribution == 'RedHat'

- name: Adding gpg key on Ubuntu
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Adding K8 repository on Ubuntu
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Disable Firewall if running on Redhat
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_distribution == 'RedHat'
  ignore_errors: true

- name: Disable SELinux on Redhat
  selinux:
    state: disabled
  when: ansible_distribution == 'RedHat'

- name: update kernel settings
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: true
  
- name: Install docker, kubeadm, and kubectl
  package:
    name: "{{item}}"
    state: present
  loop:
  - "{{necessary_packages}}"
  notify: start service

- name: Remove any host file and re-add them.
  file:
    path: /etc/hosts
    state: '{{ item }}'
    force: yes
  with_items:
  - absent
  - touch

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"
  ignore_errors: yes

- name: Disable swap.
  command: swapoff -a

- name: start service
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - "{{ services }}"