- name: Assign variable
  debug:
    var: ansible_distribution

- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ base_packages }}"

- name: Adding gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding K8 repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: update kernel settings
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: true

- name: Install docker, kubeadm, and kubectl
  package:
    name: "{{item}}"
    state: present
  loop:
  - "{{necessary_packages}}"
  notify: start service

- name: Remove any host file and re-add them.
  file:
    path: /etc/hosts
    state: '{{ item }}'
    force: yes
  with_items:
  - absent
  - touch

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"
  ignore_errors: yes

- name: Disable swap.
  command: swapoff -a

- name: start service
  service: 
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
  - "{{services}}"